### ISSUE TITLE
Fails to recognize changes in test files

### ISSUE THREAD

**Issue by tianyi-zhang** [julioleitao/codereview-file-classifier#1]
Changes in test files are not classified into the secondary category in multiple PRs. 

For example, please test https://github.com/JMRI/JMRI/pull/5345 and https://github.com/JMRI/JMRI/pull/5344.

![issue-1](https://user-images.githubusercontent.com/25597619/41012720-d83d51bc-68f7-11e8-915a-3fcf8f84656d.png)

**Comment by julioleitao** [comment]
Thanks, @tianyi-zhang !

This behavior happened because this project uses another convention that our verification don't take account.

I am adding a change at verification and make a pull request to resolve this issue.
https://github.com/julioleitao/codereview-file-classifier/pull/3
