### ISSUE TITLE
Fails to identify changes in comments 

### ISSUE THREAD

**Issue by tianyi-zhang** [julioleitao/codereview-file-classifier#2]
A line of code comment in TransBuilder.java is changed in this PR https://github.com/JMRI/JMRI/pull/5344/files

It should be identified as negligible by the ONLY_FORMAT rule---if a change only changes the format of the code but do not modify real code elements, it should be considered negligible.

But it is classified as UNDETERMINED.

![issue-2](https://user-images.githubusercontent.com/25597619/41012969-061a495e-68f9-11e8-9b7e-4a4c46656981.png)

**Comment by julioleitao** [comment]
Thanks, @tianyi-zhang !

I made the change to parse the comments at the file and classify as negligible.

The version is updated at release 0.0.2.
