### ISSUE TITLE
Some logic changes are not detected

### ISSUE THREAD

**Issue by husttroy** [julioleitao/codereview-file-classifier#5]
In [this PR](https://github.com/swagger-api/swagger-codegen/pull/8217), PetApiController.java, StoreApiController.java, and UserApiController.java all have some logic changes, e.g., the signature of their constructors are all changed. 

Also, FakeApiControllerImp.java should be identified as secondary, since the added method implements the added method in the interface, FakeApiControllerImpInterface.java.

**Comment by julioleitao** [comment]
Hi Tianyi,

That was related with the diff detection. Methods with annotations had some problems with the detection.

The branch gumtree has this fixed.

However, the src file of the controllers is not a valid Java code, there are some problems with the semicolon. We can check at the developer's comments.

> Description of the PR
> Fix missing semicolon in some controllers with async support
