### ISSUE TITLE
New test file is classified as must review

### ISSUE THREAD

**Issue by husttroy** [julioleitao/codereview-file-classifier#6]
In [this PR](https://github.com/crate/crate/pull/7252), QueryStringSplitterTest.java is a new test file. But it is identified as must review based on the NEW_CLASS_NOT_USED rule.

Shouldn't unused classes be considered secondary? Also, this is a test file. Test files are secondary at most. Please refer to the "Proposed Changes on Current Heuristics" for the lastest heuristics design.

**Comment by julioleitao** [comment]
Hi Tianyi,

The problem with QueryStringSplitterTest file is the same problem solved on the [issue 1](https://github.com/julioleitao/codereview-file-classifier/issues/1).

I had changed NEW_CLASS_NOT_USED category.
However, there is the problem if a class has some dependency on a framework. The framework will instantiate some classes. An example is a controller class at a web application.
